- .env.test
- .gitignore
- .travis.yml
- README.md
- composer.lock
- phpstan.neon.dist
- phpunit.xml.dist
- symfony.lock
As we build out the Symfony and VueJS sides of the application, we will want to ensure that PRs comply with our tests and our linters. We now have a travis-ci account and code pushes will trigger a run of travis-ci.
NOTE: I could not get phpstan to run against the tests without throwing errors. Ticket: #18
> Set up Travis for testing PRs

- config/packages/security.yaml
Added api routes with preliminary role guards to security package access_control
> Preliminary role guards on api routes

- tests/AbstractWebTestCase.php
- tests/Entity/SupplierAddressTest.php
In support of #26, add unit test coverage for Supplier Address. This test covers the only non getter/setter method in this class.
> Add Supplier Address Tests

- .travis.yml
- phpstan.neon.dist
I was able to fix issue 18 - phpstan not running in travis.
https://travis-ci.org/smrhoney/coverd/builds/601645645
https://travis-ci.org/smrhoney/coverd/builds/601642859
> fix path for phpunit in phpstan config

- tests/Entity/InventoryTransactionTest.php
In support of #26, add unit test coverage for InventoryTransaction - covering the parts of this class more complex than just getter/setter.
> Add test for InventoryTransaction

- assets/js/components/ModalConfirmBulkChange.vue
- assets/js/components/OrderMetadataBox.vue
- assets/js/components/TablePaged.vue
- assets/js/views/order/adjustment/AdjustmentOrderEdit.vue
- assets/js/views/order/adjustment/AdjustmentOrderList.vue
- assets/js/views/order/distribution/BulkDistributionOrderEdit.vue
- assets/js/views/order/distribution/BulkDistributionOrderList.vue
- assets/js/views/order/merchandise/MerchandiseOrderEdit.vue
- assets/js/views/order/merchandise/MerchandiseOrderList.vue
- assets/js/views/order/partner/PartnerOrderEdit.vue
- assets/js/views/order/partner/PartnerOrderList.vue
- assets/js/views/order/supply/SupplyOrderEdit.vue
- assets/js/views/order/supply/SupplyOrderList.vue
- assets/js/views/order/transfer/TransferOrderEdit.vue
- assets/js/views/order/transfer/TransferOrderList.vue
- src/Entity/Order.php
- src/Entity/Orders/AdjustmentOrder.php
- src/Entity/Orders/BulkDistribution.php
- src/Entity/Orders/MerchandiseOrder.php
- src/Entity/Orders/PartnerOrder.php
- src/Entity/Orders/SupplyOrder.php
- src/Entity/Orders/TransferOrder.php
- src/Entity/Sequence.php
- src/Listener/OrderListener.php
- src/Service/SequenceGenerator.php
- src/Transformers/OrderTransformer.php
Fixes #1 
All orders have their own sequence numbers and prefix. This was a request from HB so that it would be easier to reference the order if it has a prefix and incremented a order type specific sequence.
> Order sequence

- src/DataFixtures/PartnerProfileAttributeFixtures.php
- src/Entity/EAV/Attribute.php
- src/Entity/EAV/Definition.php
Closes #73 
Added fixture attribute definition to match legacy profile. Need to create a bunch more field types and UIs
> Fixtures for partner profile attributes

- assets/js/components/DisplayField.vue
- assets/js/components/NumberField.vue
- assets/js/components/OptionListEntity.vue
- assets/js/routes.js
- assets/js/store/modules/products.js
- assets/js/views/admin/ConfigurationEdit.vue
- assets/js/views/client/ClientEdit.vue
- composer.lock
- src/Controller/SystemController.php
- src/DataFixtures/BulkDistributionFixtures.php
- src/DataFixtures/ClientFixtures.php
- src/DataFixtures/SettingFixtures.php
- src/DataFixtures/UserFixtures.php
- src/Entity/Client.php
- src/Entity/Orders/BulkDistributionLineItem.php
- src/Entity/Setting.php
- src/Listener/ClientListener.php
- src/Listener/DistributionLineItemListener.php
- src/Repository/SettingRepository.php
- src/Transformers/ClientTransformer.php
This adds expirations and pullup maximum distribution.
> 85 client expirations

- src/Controller/ClientController.php
- src/Entity/Client.php
- src/Entity/Group.php
- src/Security/ClientVoter.php
Added conditional Partner filter to ClientController
Added roles to Client entity and to Group entity
Created ClientVoter
> 99 Limit visible clients to partner

- assets/js/views/product/ProductList.vue
- src/Controller/ProductController.php
- src/DataFixtures/ProductFixtures.php
- src/Entity/Product.php
- src/Entity/ProductRepository.php
- src/Transformers/ProductTransformer.php
Product.php:
+ create orderIndex property
+ getter
+ setter
ProductTransformer.php:
+ set orderIndex in transform() method
ProductFixtures.php:
+ set orderIndex to '0' on all products
ProductRepository.php:
+ create findAllSorted() method
ProductController.php
+ replace findAll() with findAllSorted() in index() method
+ create storeOrder() method
ProductList.vue:
+ add "save order" button to top-right of products list
+ add "order" column to products list table
+ set product list table as draggable
+ add arrows to product list table
+ import draggable to products list
+ add saveSort method to products list
+ add setProducts method to products list
> 91 Add custom sorting to products

- src/Controller/SupplyOrderController.php
- src/Entity/Orders/SupplyOrder.php
- src/Security/SupplyOrderVoter.php
+ create SupplyOrderVoter.php
+ make role constants public in SupplyOrder.php
+ add authorization check to SupplyOrderController.php
> 118 Supply Order Voter

- src/Controller/PartnerController.php
- src/Security/PartnerVoter.php
+ create PartnerVoter.php
+ add access checks to PartnerController.php
> 117 Partner Voter

- assets/js/components/AddressField.vue
- assets/js/components/AttributesEditForm.vue
- assets/js/components/DateField.vue
- assets/js/components/DisplayField.vue
- assets/js/components/NumberField.vue
- assets/js/components/PartnerSelectionForm.vue
- assets/js/components/ToggleField.vue
- assets/js/views/client/ClientEdit.vue
- assets/js/views/client/ClientList.vue
- src/Controller/ClientController.php
- src/Entity/Address.php
- src/Entity/Client.php
- src/Entity/EAV/Definition.php
- src/Entity/EAV/EavAddress.php
- src/Entity/EAV/Type/AddressAttribute.php
- src/Entity/EAV/Type/OptionListAttribute.php
- src/Entity/Partner.php
- src/Entity/StorageLocation.php
- src/Repository/ClientRepository.php
- src/Security/PartnerVoter.php
- src/Transformers/AddressTransformer.php
- src/Transformers/AttributeTransformer.php
- src/Transformers/ClientTransformer.php
- src/Transformers/StorageLocationTransformer.php
- tests/Controller/ClientControllerTest.php
Closes #147 
The primary purpose of this PR is adding the Address attribute type for custom fields.
This also includes some cleanup of several things including client name handling and making most props not required.
This PR also generalizes addresses for the entire system.
> Address Attribute Field and Misc Fixes

- config/packages/security.yaml
- src/Controller/AdjustmentOrderController.php
- src/Controller/ClientController.php
- src/Controller/GroupController.php
- src/Controller/MerchandiseOrderController.php
- src/Controller/OrderController.php
- src/Controller/PartnerController.php
- src/Controller/PartnerDistributionMethodController.php
- src/Controller/PartnerFulfillmentPeriodController.php
- src/Controller/PartnerOrderController.php
- src/Controller/ProductCategoryController.php
- src/Controller/ProductController.php
- src/Controller/ReportController.php
- src/Controller/StockLevelsController.php
- src/Controller/StorageLocationController.php
- src/Controller/SupplierController.php
- src/Controller/SupplyOrderController.php
- src/Controller/TransferOrdersController.php
- src/Controller/UserController.php
- src/Controller/WarehouseController.php
First attempt at assigning the appropriate roles, but in some cases I had to guess. Interested to see if this is even close to what we need.
> 126 Update API Route Security to use Annotations and Proper Roles

- composer.lock
- symfony.lock
> Update Symfony to latest patch

- config/packages/workflow.php
- src/EventSubscriber/Workflow/PartnerSubscriber.php
Closes #102 
This adds workflow guards for the Partner workflow.
> 102 add workflow permissions for partners

- assets/js/components/WarehouseSelectionForm.vue
- assets/js/routes.js
- assets/js/store/modules/storageLocations.js
- assets/js/views/order/distribution/BulkDistributionLineItemForm.vue
- assets/js/views/order/distribution/BulkDistributionLineItemFormRow.vue
- assets/js/views/order/distribution/BulkDistributionOrderEdit.vue
- src/Controller/ClientController.php
- src/Controller/PartnerController.php
- src/Controller/ProductController.php
- src/Controller/StorageLocationController.php
- src/DataFixtures/GroupFixtures.php
- src/Entity/Group.php
- src/Entity/User.php
- src/Security/PartnerVoter.php
Lots of bug fixes
Tweak permissions for partner users to do some things they need. This is not a complete review of partner use cases.
> A bunch of bug fixes

- .babelrc
- assets/js/app.js
- assets/js/routes.js
- assets/js/store/modules/system.js
- package.json
- yarn.lock
Fixes #179
The router will dispatch a user load to Vuex and the action will now skip loading if the user is already loaded.
> Fix page reload forces you back to dashboard

- src/Controller/ReportController.php
- src/Entity/Product.php
- src/Repository/ProductRepository.php
> moved ProductRepository to src/Repository

- phpstan-baseline.neon
- src/Controller/TransferOrderController.php
This PR aims to fix issue #123
> 123 Rename TransferOrdersController to follow the naming convention

- assets/js/components/AttributesEditForm.vue
- assets/js/components/TablePaged.vue
- assets/js/views/client/ClientDistributionHistory.vue
- assets/js/views/client/ClientEdit.vue
- phpstan-baseline.neon
- src/Controller/ClientController.php
- src/Controller/PartnerDistributionController.php
- src/Entity/Orders/BulkDistributionLineItem.php
- src/Repository/Orders/BulkDistributionLineItemRepository.php
- src/Transformers/BulkDistributionLineItemTransformer.php
Closes #176 
You can view a client's distribution history in the client view. The client view has been tabbed out and might need some rearranging.
> 176 client distribution history

- assets/js/components/Sidebar.vue
- assets/js/components/TableStatic.vue
- assets/js/routes.js
- assets/js/views/client/ClientSearch.vue
- src/Controller/BaseController.php
- src/Controller/ClientController.php
- src/DataFixtures/BulkDistributionFixtures.php
- src/DataFixtures/ClientFixtures.php
- src/DataFixtures/PartnerFixtures.php
- src/Repository/ClientRepository.php
Closes #189 
This provides a view for partners to search for other clients that might be duplicates or transferable. Because of the privacy implications this list is limited to 5 records.
Updated fixtures to be a little more realistic
New static table component that doesn't have paging
> #189 Client search for partners

- assets/js/components/TablePaged.vue
- assets/js/components/TableStatic.vue
- assets/js/filters/dateFormat.js
- assets/js/views/client/ClientEdit.vue
- assets/js/views/client/ClientSearch.vue
- phpstan-baseline.neon
- src/Controller/ClientController.php
- src/DataFixtures/ClientFixtures.php
- src/Entity/Client.php
- src/Repository/ClientRepository.php
- src/Transformers/ClientTransformer.php
Added parent/guardian name fields on to the Client entity and in the UI
Added birthdate to clients search in results and filter
Removed the created and updated dates
The Name search looks at the client names and the parent/guarding names
Updated fixtures to include the parent/guardian and some clients will not match on last names of the guardian.
> #226 Client Search Changes

- assets/js/components/AttributesEditForm.vue
- assets/js/components/ExceptionPane.vue
- assets/js/components/ModalOrderInvalid.vue
- assets/js/components/TablePaged.vue
- assets/js/components/TableStatic.vue
- assets/js/views/order/distribution/BulkDistributionOrderEdit.vue
- assets/js/views/order/distribution/BulkDistributionOrderList.vue
- assets/js/views/order/partner/PartnerOrderEdit.vue
- docker-compose.unison.yml
- phpstan-baseline.neon
- src/Command/ZipCountyImportCommand.php
- src/Controller/OrderController.php
- src/Controller/PartnerDistributionController.php
- src/Controller/PartnerOrderController.php
- src/Entity/Orders/BulkDistribution.php
- src/EventSubscriber/Workflow/PartnerSubscriber.php
- src/Repository/Orders/PartnerOrderRepository.php
- symfony.lock
This PR only allows one Partner Order and one Distribution Order per month.
This also fixes some icon changes after the FA upgrade
> #225 one order per month

- README.md
- bin/dockerized-install.sh
- docker/destroy.sh
- docker/down.sh
- docker/stop.sh
- docker/up.sh
These helpers make it easier to start/stop/destroy the dev environment in docker.
> Docker helpers
