happybottoms/coverd

.editorconfig, .travis.yml, CONTRIBUTING.md, README.md, docker-compose.yml, docker/app, docker/composer, docker/install, docker/yarn, phpunit.xml.dist
This is largely a documentation change with some additional changes to file formatting due to the addition of an [.editorconfig](https://editorconfig.org/) file. This is in preparation for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) #44 , which starts in just a few days.
When submitting a PR in github, github will ask the submitter if they have checked out the `CONTRIBUTING.md` if-and-only-if that file exists. This helps ensure that we get PRs with code that is properly formatted as well as issues that are more explicit.
**Note:** the amount of spaces per indent per filetype is up for debate. This is to get us started. If, at some point, we decide that, for instance, json files, require 2 spaces per indent, then that can be a separate PR.
=> Make it easier for contributors to know how to contribute

README.md
This change will make the build image actually reflect the most current master build, with a link to said build.
=> Make Build Badge dynamic with link

docker/Dockerfile
This PR adds Xdebug into the Docker container so devs can run code coverage locally, in support of #26
=> Add Xdebug for Code Coverage

.babelrc, .travis.yml, assets/js/components/AddressView.vue, assets/js/components/__tests__/AddressView.js, assets/js/components/__tests__/__snapshots__/AddressView.js.snap, jest.config.js, package.json, yarn.lock
This setups the testing infrastructure needed to get started writing the tests for #25.
A few things to be aware of:
1. Babel is no longer configured by Encore, we now have a dedicated `.babelrc` file. This is needed for Jest to be able to use Babel.
2. The `vue-jest` library currently requires a [bridge](https://github.com/vuejs/vue-jest#usage-with-babel-7) for Babel 6 -> 7. This should no longer be necessary once the next major release is available.
=> Setting up Jest and Vue Testing utils

.travis.yml, README.md
This adds PHP test coverage via [CodeClimate](https://codeclimate.com/github/happybottoms/coverd). As of this PR, Travis-CI runs the PHPUnit tests and submits the Clover coverage report to CodeClimate, which then analyzes the code coverage and lets us know which PHP files need code coverage ([Example](https://codeclimate.com/repos/5da00035611324017800c80c/settings/test_reports/5dafdec9895dd336e500a5d2)).
* Need to figure out how to get both JS and PHP code coverage. This might require storing intermediate coverage files in temporary storage somewhere (ex AWS), so I'll create a separate ticket on how to run code coverage for both JS & PHP.
* CodeClimate also provides a really nice [interface for showing where code can be improved](https://codeclimate.com/github/happybottoms/coverd/issues). …
=> Add CodeClimate coverage testing for PHP

CONTRIBUTING.md, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon.dist, src/Controller/AdjustmentOrderController.php, src/Controller/MerchandiseOrderController.php, src/Controller/OrderController.php, src/Controller/PartnerDistributionController.php, src/Controller/PartnerOrderController.php, src/Controller/SupplyOrderController.php, src/Controller/TransferOrdersController.php, src/Listener/HashPasswordListener.php
This an upgrade to PHPStan that includes bumping up our scanning level to the maximum available. The way that we are able to do this is by creating a phpstan baseline(https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff) file to scan against. Any problems that PHPStan found that are in that baseline file are ignored. Any ignored problems that are fixed will require the baseline file to be rebuilt (see adf8218 as an example of a rebuilt baseline file).
Included in this PR are:
* The PHPStan upgrade
* Increased scan level from 1 to 7 (max)
* A fix for a problem found when including `inferPrivatePropertyTypeFromConstructor: true` in the scanning properties
* Fixed docblocks to see how fixing a problem found in the baseline file …
=> Update phpstan with baseline

README.md, docker/yarn
This brings docker/yarn to how our various dockerized commands are run. 
* app --> `docker/app cmd`
* composer --> `docker/composer cmd`
**Before this change:**
It's easy to use the yarn command to watch the dev server via `docker/yarn` and convoluted to get yarn to do anything else, like run eslint: `docker/app yarn lint`
**After this change:**
* yarn cmd--> `docker/yarn cmd`
* `yarn watch` --> `docker/yarn watch`
* `yarn lint` --> `docker/yarn lint`
=> Make it easier to run dockerized yarn commands

.env.docker, README.md, docker-compose.yml, docker/Dockerfile, docker/config/app.nginx.conf
This gets xdebug working on a dev environment.
This also provides a minor speed boost using PHPs opcache. 
I followed [this as a guide](https://dev.to/brpaz/docker-phpstorm-and-xdebug-the-definitive-guide-14og). After this gets accepted, I'll create documentation for getting it working in PHPStorm.
=> Make dockerized xdebug work

src/Controller/OrderController.php, src/Controller/PartnerDistributionController.php, src/Controller/PartnerOrderController.php, src/DataFixtures/GroupFixtures.php, src/DataFixtures/PartnerOrderFixtures.php, src/Entity/Group.php, src/Entity/Order.php, src/Entity/Partner.php, src/Entity/User.php, src/Security/BulkDistributionVoter.php, src/Security/PartnerOrderVoter.php
Closes #100 
This PR adds voters for partner orders as well as adds a filter to the repository if the user doesn't have VIEW_ALL rights for the orders. This uses the "Active partner" feature to make sure lists are limited to the partner the user has selected in the case of the user being part of multiple partners.
=> Partner Order Voters

.env.docker, composer.json, composer.lock, config/bundles.php, src/Repository/UserRepository.php, symfony.lock
The scheduling bundle I'm using for the client expiration feature (#85) needs Symfony 4.4. The PR upgrades Symfony and the other libraries we are using. I've run the install script and spot checked the app, everything seems to be running just fine.
=> Symfony 4.3 to 4.4 and library upgrades

.eslintrc.json, assets/js/components/AddressView.vue, assets/js/components/DisplayField.vue, assets/js/components/KeyValueField.vue, assets/js/components/MultiOptionListEntity.vue, assets/js/components/NumberField.vue, assets/js/components/OptionListApi.vue, assets/js/components/OptionListEntity.vue, assets/js/components/OptionListStatic.vue, assets/js/components/Sidebar.vue, assets/js/components/TextField.vue, assets/js/components/TextareaField.vue, assets/js/components/ToggleField.vue, assets/js/components/Userbar.vue, assets/js/views/admin/UserEdit.vue, assets/js/views/admin/attributes/AttributeDefinitionEdit.vue, assets/js/views/admin/attributes/AttributeDefinitionList.vue, assets/js/views/admin/attributes/ClientAttributeDefinitionEdit.vue, assets/js/views/admin/attributes/PartnerAttributeDefinitionEdit.vue, assets/js/views/order/distribution/BulkDistributionLineItemForm.vue, assets/js/views/partner/PartnerLocationEditTab.vue, assets/js/views/product/ProductCategoryView.vue, assets/js/views/warehouse/WarehouseList.vue, package.json, src/Entity/Client.php, src/Entity/Partner.php, src/Entity/User.php, src/Transformers/UserTransformer.php, yarn.lock
This fixes #108 
**Note:** This PR will be easier to review commit-by-commit since each commit can stand alone and takes care of a specific kind of fix.
PHP in the master branch was not getting built by the CI due to a lint error.
This PR fixes:
* Warning about line length for some exceptions we were throwing. See: fd809b9be5
JS in the master branch was not getting built by the CI due to several eslint errors.
This PR fixes:
* Errors and Warnings via `yarn lint --fix`
* Errors via removing unused components from `UserEdit`. See: 6f90dc4
* A conditional-chaining error because eslint doesn't know what conditional-chaining is
* It knows what conditional-chaining is now. See: 35ca85797c66
* Error about mixing `v-for` and `v-if`. The fix actually simplifies the code, so yay! See: …
=> Fix build errors

assets/js/views/client/ClientEdit.vue, assets/js/views/partner/PartnerEdit.vue, composer.json, composer.lock, config/bundles.php, config/packages/workflow.php, src/Command/ClientExpirationCommand.php, src/Controller/ClientController.php, src/Controller/PartnerController.php, src/Entity/Client.php, src/Entity/Partner.php, src/Repository/ClientRepository.php, src/Schedule/ClientExpirationSchedule.php, symfony.lock
Closes #85 
This PR creates a command that will find all active clients and transition them to the Expired status if they are past an expiration date in the entity. This also uses the zenstruck scheduler to schedule that command to run daily overnight.
I refactored a bit of the workflow response so that we can control the frontend user visible title of the transitions so that we can make changes to that easily if the bank needs it, and we don't have to rely on title casing the machine names. I also used constants for the transition machine name so that we can control transitions and states in the entity.
=> 85 client expiration transitions

src/Controller/AdjustmentOrderController.php, src/Controller/SupplyOrderController.php, src/Controller/TransferOrdersController.php, src/Entity/Orders/SupplyOrder.php, src/Security/AdjustmentOrderVoter.php, src/Security/SupplyOrderVoter.php, src/Security/TransferOrderVoter.php
@akoebbe The resulting behavior is that when clicked, `Adjustments > Stock Changes` and `Adjustments > Transfer Orders` in the navigation, simply do nothing, which isn't as user-friendly as I'm sure we'd like it to be. Just a thought! Thanks again!
=> 119 Adjustment and Transfer Order Voter

src/Controller/ClientController.php
After reviewing the vue library that creates the table info, I realized the "to" value was a pass-through from the API response. I updated the controller to use the smaller value between the page limit or total found. I considered if there should be a factory for the pagination meta, as this would apply to all API endpoints that provide it.
Resolves #111. 
How it used to look:
How it looks now:
=> Use total for pagination info when less than page limit

config/packages/doctrine.yaml, src/Controller/OrderController.php
Closes #139 
Fixed how the line item processor dealt with empty IDs
Also found that the soft delete extension was not fully configured. The doctrine filter was not set up and therefore deleted items still showed up.
=> #139 - Error saving supply orders

assets/js/components/AttributesEditForm.vue, assets/js/components/DateField.vue, assets/js/components/NumberField.vue, assets/js/components/OptionListApi.vue, assets/js/components/RadioField.vue, assets/js/components/TextField.vue, assets/js/components/TextareaField.vue, assets/js/components/ToggleField.vue, assets/js/components/YesNoRadioField.vue, assets/js/views/admin/attributes/AttributeDefinitionEdit.vue, assets/sass/_happybottoms.scss, src/Entity/EAV/Definition.php, src/Transformers/AttributeDefinitionTransformer.php, src/Transformers/AttributeTransformer.php
This update should give you the ability to add custom help text (of max-length 255) to any Client or Partner Attribute. The uri to try that out is: /#/admin/attributes/client ...
Once you have added help text to any attributes, you should then see a little icon with a tooltip next to its corresponding label on the detail page found under Client Management or Partner Management. Those uris are: /#/clients + /#/partners
Of course we can display these hints however you wish. 2 screenshots are attached to see v1.
Let me know what you think!
=> 74 Add help text property for attribute fields

src/Controller/ClientController.php, src/DataFixtures/ClientFixtures.php, src/DataFixtures/PartnerFixtures.php
This started out as a way to resolve #152, but the effort was duplicated by #153 . This evolved from there.
This fixes fixtures so active clients load with populated partners and new clients can be created with an active partner.
Resolves #152
=> 152 cannot create client

src/EventSubscriber/Workflow/ClientSubscriber.php, src/Security/ClientVoter.php
Fixes 103 by adding a client subscriber that acts a client workflow guards. The guards are using the Client Voter.
The change looks simple enough, but the difficulty was in learning how to do this simple change in the first place :)
=> 103 add workflow permissions for clients

src/Entity/Client.php
When a blank status was being sent by the UI, a blank status was getting creating in the DB. Now a check is made for proper statuses being sent and, if none is provided, the default "CREATION" status is used.
Fixes #173
=> 173 Status not getting set when creating a client

src/EventSubscriber/Workflow/ClientSubscriber.php
Fixes #182 
This was tested by finding an active partner, finding that partner's email address, and logging in as that partner. I then went to Client Management and clicked on a client. I could then transition between only Active and Inactive, no other transitions were available to me as a partner user.
=> Ensure Partners Can Activate and Deactivate Clients

src/Controller/ProductCategoryController.php, src/Entity/ProductCategory.php, src/Entity/ProductCategoryRepository.php
As discussed under #216 I have added some validation logic for deleting the ProductCategory entity.
When ProductCategory has related Product entities which have not been deleted then the user will be presented with the following error: Cannot delete a category which has related products
=> Add validation logic to product category deletion

assets/js/views/client/ClientList.vue, src/Repository/ClientRepository.php
At the moment the API responds with status code 500 due to `fullName` not being an actual column. I updated it to sort by `firstname`. 
Should this be `ORDER BY firstname DESC, lastname DESC` instead? However this would create an if clause to the repository class.
I also noticed issue #30 however at the moment I am not sure how to provide a generic solution for all cases. This PR aims to be a quick fix so that the users will not experience unexpected behavior.
=> 151 Fix client name sorting

tests/Controller/ClientControllerTest.php, tests/Entity/InventoryTransactionTest.php
AssertSame reports an error if the two elements do not share type and value.
For example: this code `$this->assertEquals(3, true);` give uns true, because it won't check the type.
Its saver to use assertSame instead of assertEquels.
=> changed assertEquels to assertSame

assets/js/components/ProductSelectionField.vue, assets/js/components/Sidebar.vue, assets/js/routes.js, assets/js/views/order/distribution/BulkDistributionLineItemFormRow.vue
Closes #10 
The logic for showing menu items base on the user's role wasn't working right. We were also showing the 1st level nav even if it didn't have any sub-menu items.
Bonus product selection component fixes.
=> #10 Show menu items only if the user has access to them

assets/js/app.js, assets/js/components/OrderMetadataBox.vue, assets/js/components/PartnerSelectionForm.vue, assets/js/store/modules/storageLocations.js, assets/js/views/admin/ConfigurationEdit.vue, assets/js/views/order/partner/PartnerOrderEdit.vue, assets/sass/_happybottoms.scss, config/packages/workflow.php, config/services.yaml, phpstan-baseline.neon, src/Command/ClientExpirationCommand.php, src/Command/PartnerAnnualReviewCommand.php, src/Configuration/AppConfiguration.php, src/Controller/PartnerOrderController.php, src/Controller/SystemController.php, src/DataFixtures/BaseFixture.php, src/DataFixtures/PartnerFixtures.php, src/DataFixtures/SettingFixtures.php, src/Entity/Partner.php, src/Entity/Setting.php, src/EventSubscriber/Workflow/PartnerSubscriber.php, src/Listener/PartnerListener.php, src/Schedule/ClientExpirationSchedule.php, src/Schedule/PartnerReviewSchedule.php, src/Transformers/PartnerTransformer.php, src/Transformers/StorageLocationTransformer.php
Closes #195 
Partner Review start and end dates have been added to the settings, plus the time of the last start and end job were run. There is a schedule class that takes care of the recurring nature of this command.
When the review period starts, all "Active" partners will moved to "Needs Review". After the end of the review period, the command will change all "News Review" to "Review Past Due". The latter will prevent that partner from placing any more orders. If a partner update's their partner record in any of the review statuses, the partner will change back to "Active".
=> 195 partner review

assets/js/components/order/LineItemByClientFormRow.vue, assets/js/views/order/partner/PartnerOrderEdit.vue, src/Entity/Client.php, src/Entity/Orders/BulkDistributionLineItem.php, src/Transformers/ClientTransformer.php
In the partner order screen the users now sees the product and quantity the client was given in the last distribution. This will make it easier to reorder the same size for a client.
=> 200 partner order show previous client dist

assets/js/components/AttributesEditForm.vue, assets/js/routes.js, assets/js/views/admin/attributes/AttributeDefinitionEdit.vue, assets/js/views/admin/attributes/AttributeDefinitionList.vue, assets/js/views/admin/attributes/ClientAttributeDefinitionEdit.vue, assets/js/views/admin/attributes/ClientAttributeDefinitionList.vue, assets/js/views/admin/attributes/PartnerAttributeDefinitionList.vue, assets/js/views/client/ClientEdit.vue, assets/js/views/client/ClientInfoForm.vue, assets/js/views/client/ClientNewCheck.vue, src/Controller/BaseController.php, src/Controller/ClientAttributeDefinitionController.php, src/Controller/ClientController.php, src/Entity/EAV/ClientDefinition.php, src/Entity/EAV/Definition.php, src/Listener/ClientListener.php, src/Repository/ClientRepository.php, src/Transformers/AttributeTransformer.php, src/Transformers/ClientAttributeDefinitionTransformer.php, src/Transformers/ClientAttributeTransformer.php, src/Transformers/ClientTransformer.php, tests/Controller/ClientControllerTest.php
This adds a new "New Client" view that will give the user a subset of fields they need to enter to check of duplicates. If there are no duplicates, it will provide them with the rest of the fields to create the client. If there are duplicates, it will present the user with a list of duplicate clients. Later ticket will add the ability to transfer a client to their agency from that list.
To support this feature, the hard coded client fields were extracted in to its own component so that it can be used in the edit and new client screen.
This also adds a flag for custom fields to be included when checking for duplicates.
=> 174 client creation duplicate check

assets/js/components/TableStatic.vue, assets/js/store/modules/system.js, assets/js/views/client/ClientNewCheck.vue, assets/js/views/client/ClientSearch.vue, assets/js/views/client/ClientTransferModal.vue, phpstan-baseline.neon, src/Controller/ClientController.php, src/Entity/Client.php, src/Security/ClientVoter.php, src/Transformers/ClientTransformer.php
Client Transfer
If a client is Inactive a partner can transfer that client to their current active partner by click new buttons on either the Client Search or Duplicate check when creating a new client. This has to be done as a logged in partner. Managers/Admins should change the partner through the client edit screen.
=> 175 transfer clients
